### ISSUE TITLE
The cooperative vehicles in 'tfs' and 'coop_cloud' are different?

### ISSUE THREAD

**Issue by yifanlu0227** [YuanYunshuang/FPV_RCNN#2]
Hi, I download your COMAP dataset and extract them all, but find them confusing. The cooperative vehicles in 'tfs' and 'coop_cloud' have no correspondence

Take the first frame in train_val.txt as example, 1070_000317.

keys in tfs/1070_000317.npy include ['tf_ego', '000578',''000573'',''000561'']

files in coop_cloud/1070_000317 include ['000388.bin', '000447.bin', '000386.bin', '000414.bin', '000458.bin', '000387.bin', '000391.bin', '000399.bin', '000405.bin']. And them will turn to coop_ids.

so I encounter error in line 116 in datasets/comap/comap.py, which says a key error.

**Comment by YuanYunshuang** [comment]
Hi, thank you for pointing this out. The data is updated. It should now contain the pose information of each cooperative vehicle.

**Comment by yifanlu0227** [comment]
Thanks! And I have another question, in some coop point cloud bin file (e.g. 'cloud_coop/1162_000356/000797.bin"), the element number are not divisible by 4. 

So the code in comap.py line 204 will cause error.
`cloud_coop = np.fromfile(coop_files[cf], dtype="float32").reshape(-1, 4)`

How to fix it?

**Comment by YuanYunshuang** [comment]
> Thanks! And I have another question, in some coop point cloud bin file (e.g. 'cloud_coop/1162_000356/000797.bin"), the element number are not divisible by 4.
> 
> So the code in comap.py line 204 will cause error. `cloud_coop = np.fromfile(coop_files[cf], dtype="float32").reshape(-1, 4)`
> 
> How to fix it?

Hi, I tried to read the file "cloud_coop/1162_000356/000797.bin" and did not meet the problem. Could you please try to pull the code (I updated something) and try to run it again? Or just run
```python
np.fromfile("cloud_coop/1162_000356/000797.bin", dtype="float32").reshape(-1, 4)
``` 
in python console to check if it is really a problem of the data?

**Comment by yifanlu0227** [comment]
Sorry! this bin file is correct and divisible by 4. But there are some other files seem to have problem. 
`pc = np.fromfile("cloud_coop/1070_000087/000399.bin",dtype='float32')`
`pc.shape # (57609,)`

`pc = np.fromfile("cloud_coop/1162_000461/000775.bin",dtype='float32')`
`pc.shape # (51987,)`

**Comment by YuanYunshuang** [comment]
Please use the new uploaded "cloud_coop_with_label".
