### ISSUE TITLE
COMAP dataset cannot download

### ISSUE THREAD

**Issue by yuanzhenhuan** [YuanYunshuang/FPV_RCNN#4]
hello, I can't download the COMAP dataset. The link https://seafile.cloud.uni-hannover.de/d/1c52826e98d34c0399a4/  interface's shows that '/COMP/' does not exist.

**Comment by YuanYunshuang** [comment]
Sorry for the delay, here is the new link 
https://seafile.cloud.uni-hannover.de/f/cb3e9e25646b4119a5e6/?dl=1
