### ISSUE TITLE
images and segmantation

### ISSUE THREAD

**Issue by melihyazgan** [YuanYunshuang/FPV_RCNN#5]
Greetings,

I can not find any image in data and corresponding ground truth data for semantic segmentations.

Regards,
Melih

**Comment by YuanYunshuang** [comment]
Sorry for the confusion, the originally generated data was accidentally deleted. So the link shared now is a replacement only with the point clouds and ground truth bounding boxes. If you want to have other ground truth you can try running the simulation starting from the example code [here](https://github.com/YuanYunshuang/cosense-simulation) . 

By the way, the repo is not maintained anymore. We are about to open another bigger project including the implementation of FPVRCNN and a new dataset with more realistic features.

**Comment by melihyazgan** [comment]
thank you for your comment. I am happy to hear about the new project.
